GUIDE = (
    "👑 **Tacloban HQ v2.3.0**\n"
    "I can help you manage your multi-account outreach. "
    "For system documentation, see your GitHub README.\n\n"
    "**You can control the engine by sending these commands:**\n\n"
    "/send_now - 🚀 Trigger immediate manual blast\n"
    "/schedule - 📅 Set date/time for auto-send\n\n"
    "**Manage Operations**\n"
    "/status - 📊 View global audit & stats\n"
    "/add_list - 📂 Import new @username list\n"
    "/edit_msg - 📝 Update promotional text\n"
    "/add_account - 📱 Link new sender session\n\n"
    "**Engine Control**\n"
    "/pause_send - ⏸️ Stop active manual sending\n"
    "/pause_sched - ⏸️ Stop active scheduled tasks\n\n"
    "*Everything is synced to Asia/Manila (PHT).*"
)
